musee_collection_afficher_liste:
    pattern:  /liste/{page}
    defaults: { _controller: MuseeCollectionBundle:Collection:afficherListeObjet }
    requirements:
        annee:  \d

musee_collection_ajouter:
    pattern:  /ajouter
    defaults: { _controller: MuseeCollectionBundle:Collection:ajouterObjet }

musee_collection_supprimer:
    pattern:  /supprimer/{id}
    defaults: { _controller: MuseeCollectionBundle:Collection:supprimerObjet }

musee_collection_modifier:
    pattern:  /modifier/{id}
    defaults: { _controller: MuseeCollectionBundle:Collection:modifierObjet }

musee_collection_afficher:
    pattern:  /afficher/{id}
    defaults: { _controller: MuseeCollectionBundle:Collection:afficherObjet }

musee_collection_plan:
    pattern:  /plan
    defaults: { _controller: MuseeCollectionBundle:Collection:plan }