parameters:
#    musee_collection.example.class: Musee\CollectionBundle\Example

services:
#    musee_collection.example:
#        class: %musee_collection.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
