musee_user:
    resource: "@MuseeUserBundle/Resources/config/routing.yml"
    prefix:   /

musee_collection:
    resource: "@MuseeCollectionBundle/Resources/config/routing.yml"
    prefix:   /collection

musee_blog:
    resource: "@MuseeBlogBundle/Resources/config/routing.yml"
    prefix:   /article

musee_site:
    resource: "@MuseeSiteBundle/Resources/config/routing.yml"
    prefix:   /museeKourou


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
