jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Musee\UserBundle\Entity\User: sha512


    role_hierarchy:
        ROLE_ADMIN:       [ROLE_CHERCHEUR, ROLE_ADHERENT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        musee:
            chain:
                providers: [musee_user, in_memory]

        musee_user:
            entity: { class: MuseeUserBundle:User, property: username }

        in_memory:
            memory:
                users:
                    chercheur@kourou.fr:  { password: kourou, roles: [ 'ROLE_CHERCHEUR' ] }
                    admin@kourou.fr: { password: kourou, roles: [ 'ROLE_ADMIN' ] }
                    adherent@kourou.fr: { password: kourou, roles: [ 'ROLE_ADHERENT' ] }
        
    firewalls:

        

        secured_area:
            pattern:    ^/
            anonymous: ~
            provider:  musee
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /museeKourou
                always_use_default_target_path: true
                
            logout:
                path:   /logout
                target: /museeKourou

            

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/profil, roles: IS_AUTHENTICATED_ANONYMOUSLY }
