<?php

namespace Musee\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfoSupplementaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoSupplementaireRepository extends EntityRepository
{
}
