musee_site_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MuseeSiteBundle:Default:index }

musee_accueil:
    pattern:  /
    defaults: { _controller: MuseeSiteBundle:Site:index }

musee_aPropos:
    pattern:  /apropos
    defaults: { _controller: MuseeSiteBundle:Site:aPropos }

musee_contact:
    pattern: /contact
    defaults: { _controller: MuseeSiteBundle:Site:contact }

musee_infosPratiques:
    pattern: /infosPratiques
    defaults: { _controller: MuseeSiteBundle:Site:infosPratiques }

musee_mail:
    pattern: /mail
    defaults: { _controller: MuseeSiteBundle:Site:mail }
    requirements:
        _method:  GET|POST

musee_pageEnregistrementAdmin:
    pattern:  /admin/register
    defaults: { _controller: MuseeSiteBundle:Site:register }

musee_pageListeModifUserAdmin:
    pattern:  /admin/modifier/liste
    defaults: { _controller: MuseeSiteBundle:Site:afficherModif }

musee_pageListeSupprUserAdmin:
    pattern:  /admin/supprimer/liste
    defaults: { _controller: MuseeSiteBundle:Site:afficherSuppr }

