musee_site_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MuseeSiteBundle:Default:index }

musee_accueil:
    pattern:  /
    defaults: { _controller: MuseeSiteBundle:Site:index }
