<?php

namespace Musee\CollectionBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator; //pour la pagination

/**
 * ObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetRepository extends EntityRepository
{
	public function getObjets($nombreParPage, $page)
	{
		$query = $this 	-> createQueryBuilder('o')
						-> leftJoin('o.image', 'i')
							->addSelect('i')
						-> leftJoin('o.statutObjet', 's')
							->addSelect('s')
						-> leftJoin('o.typeObjet', 't')
							->addSelect('t')
						-> orderBy('s.dateAquisition', 'DESC')
						-> getQuery();
						
		$query -> setFirstResult(($page-1) * $nombreParPage)
			   -> setMaxResults($nombreParPage);
		
		return new Paginator($query);
	}
}
