<?php

namespace Musee\CollectionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalleStockageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleStockageRepository extends EntityRepository
{
}
