<?php

namespace Musee\CollectionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeObjetRepository extends EntityRepository
{
}
