<?php

namespace Musee\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeArticleRepository extends EntityRepository
{
}
