musee_blog_ajouter:
    pattern:  /ajouter
    defaults: { _controller: MuseeBlogBundle:Article:ajouterArticle }

musee_blog_afficher_liste:
    pattern:  /afficher/{page}
    defaults: { _controller: MuseeBlogBundle:Article:afficherListeArticle }
    requirements:
        page: \d

musee_blog_modifier:
    pattern: /modifier/{slug}
    defaults: { _controller: MuseeBlogBundle:Article:modifierArticle }

musee_blog_supprimer:
    pattern:  /supprimer/{slug}
    defaults: { _controller: MuseeBlogBundle:Article:supprimerArticle }

musee_blog_afficher:
    pattern: /afficher/{slug}
    defaults: { _controller: MuseeBlogBundle:Article:afficherArticle }