musee_blog_ajouter:
    pattern:  /ajouter
    defaults: { _controller: MuseeBlogBundle:Article:ajouter }

musee_blog_afficher:
    pattern:  /afficher/{id}
    defaults: { _controller: MuseeBlogBundle:Article:afficher }