parameters:
#    musee_blog.example.class: Musee\BlogBundle\Example

services:
#    musee_blog.example:
#        class: %musee_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
