musee_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MuseeUserBundle:Default:index }

musee_pageAdmin:
    pattern: /admin
    defaults: { _controller: MuseeUserBundle:Admin:pageAdmin }

musee_create_user_admin:
    pattern: /user/createAdmin
    defaults: { _controller: MuseeUserBundle:Registration:registerAdmin }

musee_create_user_adherent:
    pattern: /user/createAdherent
    defaults: { _controller: MuseeUserBundle:Registration:registerAdherent }

musee_create_user_chercheur:
    pattern: /user/createChercheur
    defaults: { _controller: MuseeUserBundle:Registration:registerChercheur }

login:
    pattern: /login
    defaults: { _controller: MuseeUserBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout
