musee_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MuseeUserBundle:Default:index }

musee_pageAdmin:
    pattern: /admin
    defaults: { _controller: MuseeUserBundle:Admin:pageAdmin }

musee_create_user:
    pattern: /user/create
    defaults: { _controller: MuseeUserBundle:Registration:register }

login:
    pattern: /login
    defaults: { _controller: MuseeUserBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout
