musee_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MuseeUserBundle:Default:index }

musee_pageAdmin:
    pattern: /admin
    defaults: { _controller: MuseeUserBundle:Admin:pageAdmin }

musee_create_user_admin:
    pattern: /user/createAdmin
    defaults: { _controller: MuseeUserBundle:Registration:registerAdmin }

musee_create_user_adherent:
    pattern: /user/createAdherent
    defaults: { _controller: MuseeUserBundle:Registration:registerAdherent }

musee_create_user_chercheur:
    pattern: /user/createChercheur
    defaults: { _controller: MuseeUserBundle:Registration:registerChercheur }

musee_confirm_inscription:
    pattern: /user/confirm/{token}
    defaults: { _controller: MuseeUserBundle:Registration:confirm }

musee_modif_user_liste:
    pattern: /user/modifListe/{page}
    defaults: { _controller: MuseeUserBundle:Modif:modifListe }

musee_modif_user:
    pattern: /user/modifUser/{id}
    defaults: { _controller: MuseeUserBundle:Modif:modifier }

musee_suppr_user:
    pattern: /user/supprUser/{id}
    defaults: { _controller: MuseeUserBundle:Modif:supprimer }

musee_suppr_user_confirm:
    pattern: /user/supprConfirmUser/{id}
    defaults: { _controller: MuseeUserBundle:Modif:supprConfirm }

musee_suppr_user_liste:
    pattern: /user/supprListe/{page}
    defaults: { _controller: MuseeUserBundle:Modif:supprListe }

login:
    pattern: /login
    defaults: { _controller: MuseeUserBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout
