parameters:
#    musee_user.example.class: Musee\UserBundle\Example

services:
    musee_user.registration.form.type:
        class: Musee\UserBundle\Form\Type\RegistrationFormType
        arguments: [%security.role_hierarchy.roles%]
        tags:
            - { name: form.type, alias: musee_user_registration }
