parameters:
#    musee_user.example.class: Musee\UserBundle\Example

services:
    musee_user.registration.form.type:
        class: Musee\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acme_user_registration }
