parameters:
#    musee_user.example.class: Musee\UserBundle\Example

services:
#    musee_user.example:
#        class: %musee_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
